swagger: "2.0"
info:
  description: "Clean Architecture Basic API"
  version: "1.0.0"
  title: "Clean Architecture"
  contact:
    email: "david.garzon@gmail.com"
basePath: "/api/v1"
tags:
  - name: "Offers"
    description: "Offers Management"
  - name: "Users"
    description: "Users Management"
schemes:
  - "http"
  - "https"
paths:
  /offers:
    get:
      tags:
        - "Offers"
      description: "Get all offers"
      operationId: "getOffers"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Bad request"
    post:
      tags:
        - "Offers"
      description: "Create an offer"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: "name"
          type: "string"
          description: "Offer name"
          default: "New offer"
          required: true
        - in: formData
          name: "description"
          type: "string"
          description: "Offer description"
          default: "New description"
          required: true
        - in: formData
          name: "image"
          type: "file"
          description: "Offer image"
      operationId: "addOfer"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Offer name already created"
  /offers/{offerId}:
    put:
      tags:
        - "Offers"
      description: "Updates an offer"
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: "offerId"
          type: "string"
          description: "Offer id"
          required: true
        - in: formData
          name: "name"
          type: "string"
          description: "Offer name"
          default: "New offer"
        - in: formData
          name: "description"
          type: "string"
          description: "Offer description"
          default: "New description"
      operationId: "updateOffer"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Bad request"
  /users:
    get:
      tags:
        - "Users"
      description: "Get all users"
      operationId: "getUsers"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Bad request"