swagger: "2.0"
info:
  description: "Clean Architecture Basic API"
  version: "1.0.0"
  title: "Clean Architecture"
  contact:
    email: "david.garzon@gmail.com"
host: "localhost:8080"
basePath: "/api/v1"
tags:
  - name: "Offers"
    description: "Offers Management"
schemes:
  - "http"
  - "https"
paths:
  /offers:
    post:
      parameters:
        - in: "body"
          name: "body"
          description: "Offer data for creation"
          required: true
          schema:
            $ref: "#/definitions/Offer"
      operationId: "addOfer"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Offer name already created"
    get:
      operationId: "getOffers"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Bad request"
  /users:
    get:
      operationId: "getUsers"
      responses:
        "200":
          description: "Successful response"
        "400":
          description: "Offer name already created"
definitions:
  Offer:
    type: "object"
    properties:
      name:
        type: "string"
        default: "Offer 1"
      description:
        type: "string"
        default: "Offer description"
    xml:
      name: "Offer"
